services:
  - type: web
    name: flowup-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RESTAURANT_ID
        value: FLOWUP001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_ORIGIN
        sync: false
      - key: CUSTOMER_ORIGIN
        sync: false
      - key: WAITER_ORIGIN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        sync: false
